#!/usr/bin/env python3
"""Generate/check the source fingerprint embedded in diagnostic META."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "imcalib/Telemetry/s2r_build_info.h"


def source_digest():
    digest = hashlib.sha256()
    paths = []
    for folder in ("Core", "imcalib", "X-CUBE-AI/App"):
        paths.extend(p for p in (ROOT / folder).rglob("*") if p.suffix in (".c", ".h") and p != TARGET)
    for p in sorted(paths):
        digest.update(p.relative_to(ROOT).as_posix().encode() + b"\0" + p.read_bytes())
    return digest.hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    digest = source_digest()
    if args.check:
        if not TARGET.exists() or f'#define S2R_SOURCE_SHA256 "{digest}"' not in TARGET.read_text():
            raise SystemExit("META source fingerprint is stale; run tools/s2r_build_info.py before building")
        print("META source fingerprint matches")
        return
    base = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
    dirty = bool(subprocess.check_output(["git", "status", "--porcelain"], cwd=ROOT, text=True).strip())
    network = (ROOT / "X-CUBE-AI/App/networkzn1.c").read_text()
    signature = re.search(r'AI_NETWORKZN1_MODEL_SIGNATURE\s+"0x([0-9a-fA-F]+)"', network).group(1)
    header = (ROOT / "X-CUBE-AI/App/networkzn1.h").read_text()
    name = re.search(r'AI_NETWORKZN1_ORIGIN_MODEL_NAME\s+"([^"\n]+)"', header).group(1)
    model = {"name": name + ".onnx", "hash_algorithm": "MD5", "hash": signature,
             "backend": "STM32Cube.AI", "input_shapes": [[1, 25], [1, 125]],
             "output_shapes": [[1, 6], [1, 3]], "numeric_type": "float32"}
    build = {"base_commit": base, "dirty_at_generation": dirty, "source_sha256": digest,
             "identity_rule": "source digest identifies the source set; regenerate before every build"}
    config = hashlib.sha256((ROOT / "imcalib/user-lib/machine_config.c").read_bytes()).hexdigest()
    literal = lambda obj: json.dumps(json.dumps(obj, separators=(",", ":")))
    TARGET.write_text("/* Generated by tools/s2r_build_info.py. */\n#ifndef S2R_BUILD_INFO_H\n#define S2R_BUILD_INFO_H\n"
                      f'#define S2R_SOURCE_SHA256 "{digest}"\n'
                      f'#define S2R_CONFIG_SHA256 "{config}"\n'
                      f'#define S2R_BUILD_JSON {literal(build)}\n'
                      f'#define S2R_MODEL_JSON {literal(model)}\n#endif\n')
    print(TARGET)


if __name__ == "__main__":
    main()
