/* Generated by tools/firmware_build_info.py. */
#ifndef FIRMWARE_BUILD_INFO_H
#define FIRMWARE_BUILD_INFO_H
#define FIRMWARE_SOURCE_SHA256 "36132a04a05891d0287d9f8a5a37d32fbe69fc03910e0b919eb95db98da3356f"
#define FIRMWARE_CONFIG_SHA256 "a3d83ea3c2d2bd3061c83bccad5c0e88e36d0df5e9a53deaad8bc1193f81bc8d"
#define FIRMWARE_BUILD_JSON "{\"base_commit\":\"b388bbebccc1d65c917cca1a25c7c90d13cdb680\",\"dirty_at_generation\":true,\"source_sha256\":\"36132a04a05891d0287d9f8a5a37d32fbe69fc03910e0b919eb95db98da3356f\",\"identity_rule\":\"source digest identifies the source set; regenerate before every build\"}"
#define FIRMWARE_MODEL_JSON "{\"name\":\"model_15000_h723.onnx\",\"hash_algorithm\":\"MD5\",\"hash\":\"dca19cdb9c3745a6133481ab657e7d4b\",\"backend\":\"STM32Cube.AI\",\"input_shapes\":[[1,25],[1,125]],\"output_shapes\":[[1,6],[1,3]],\"numeric_type\":\"float32\"}"
#endif
