/* Generated by tools/s2r_build_info.py. */
#ifndef S2R_BUILD_INFO_H
#define S2R_BUILD_INFO_H
#define S2R_SOURCE_SHA256 "5bff26d44023cf32ca7418b940745a57f4aef35b72800b0b57671f1a923164e5"
#define S2R_CONFIG_SHA256 "70059618c025373eeb25e73ccdef33edba92fab1ceaf95c3c705310f7be05a83"
#define S2R_BUILD_JSON "{\"base_commit\":\"a824da146092b4b6f1e736259f1e702fda6c36d0\",\"dirty_at_generation\":true,\"source_sha256\":\"5bff26d44023cf32ca7418b940745a57f4aef35b72800b0b57671f1a923164e5\",\"identity_rule\":\"source digest identifies the source set; regenerate before every build\"}"
#define S2R_MODEL_JSON "{\"name\":\"model_6000_h723.onnx\",\"hash_algorithm\":\"MD5\",\"hash\":\"4899195601babb22a7c0b46cc151ad84\",\"backend\":\"STM32Cube.AI\",\"input_shapes\":[[1,25],[1,125]],\"output_shapes\":[[1,6],[1,3]],\"numeric_type\":\"float32\"}"
#endif
